name: Daily Keep-Awake Summary

on:
  schedule:
    - cron: "5 0 * * *"   # every day at 00:05 UTC
  workflow_dispatch:

permissions:
  contents: read

jobs:
  daily:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PING_URL: https://gifts-api.onrender.com/health
    steps:
      - name: Show UTC time
        run: date -u

      - name: Daily summary ping (with retries)
        run: |
          set -euxo pipefail
          for i in 1 2 3; do
            if OUT="$(curl -sfL --max-time 20 "$PING_URL")"; then
              echo "✅ Daily summary: endpoint reachable."
              echo "Response: $OUT"
              exit 0
            fi
            echo "Attempt $i failed; retrying..."
            sleep 20
          done
          echo "❌ Daily summary: endpoint NOT reachable after 3 attempts."
          exit 1
