name: Keep Render Awake (5m)

on:
  schedule:
    - cron: "*/5 * * * *"   # every 5 minutes (UTC)
  workflow_dispatch:        # allow manual run

# Avoid overlapping runs
concurrency:
  group: keep-render-awake
  cancel-in-progress: false

permissions: {}

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    env:
      PING_URL: https://gifts-api.onrender.com/health
    steps:
      - name: Show UTC time
        run: date -u

      - name: Ping Render health endpoint (3 retries)
        run: |
          set -euxo pipefail
          for i in 1 2 3; do
            if curl -sfL --max-time 10 "$PING_URL"; then
              echo "Ping succeeded on attempt $i"
              exit 0
            fi
            echo "Attempt $i failed; sleeping before retry..."
            sleep 20
          done
          echo "All attempts failed"
          exit 1
