name: Keep Render Awake

on:
  schedule:
    - cron: "*/10 * * * *"   # every 10 minutes (UTC)
  workflow_dispatch:          # allows manual run from the Actions tab

# Avoid overlapping runs if a previous one is slow
concurrency:
  group: keep-render-awake
  cancel-in-progress: false

permissions: {}               # least-privilege (this job doesn't need repo perms)

jobs:
  ping:
    runs-on: ubuntu-latest
    timeout-minutes: 5

    env:
      PING_URL: https://gifts-api.onrender.com/health

    steps:
      - name: Show UTC time
        run: date -u

      - name: Ping Render health endpoint (with retries)
        run: |
          set -euxo pipefail
          # Try up to 3 times to handle transient network hiccups
          for i in 1 2 3; do
            if curl -sfL --max-time 10 "$PING_URL"; then
              echo "Ping succeeded on attempt $i"
              exit 0
            fi
            echo "Attempt $i failed; sleeping before retry..."
            sleep 20
          done
          echo "All attempts failed"
          exit 1
